/*
 * Script para criar a tabela de histórico de alterações (auditoria).
 * Execute no Firebird para gravar e exibir exclusões de comandas e outras ações.
 */
CREATE TABLE HISTORICO_ALTERACOES (
    ID INTEGER NOT NULL PRIMARY KEY,
    TIPO VARCHAR(50) NOT NULL,
    ENTIDADE_ID VARCHAR(50) NOT NULL,
    ACAO VARCHAR(50) NOT NULL,
    OPERADOR INTEGER NOT NULL,
    NOME_OPERADOR VARCHAR(100),
    DATA_HORA TIMESTAMP NOT NULL,
    DESCRICAO VARCHAR(500),
    DADOS_ANTIGOS BLOB SUB_TYPE TEXT,
    DADOS_NOVOS BLOB SUB_TYPE TEXT,
    OBSERVACOES VARCHAR(500)
);

CREATE GENERATOR GEN_HISTORICO_ALTERACOES_ID;

SET TERM ^ ;
CREATE TRIGGER TR_HISTORICO_ALTERACOES_BI FOR HISTORICO_ALTERACOES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_HISTORICO_ALTERACOES_ID, 1);
END^
SET TERM ; ^

COMMIT;
