-- ============================================
-- DIAGNÓSTICO: Problema com Grupo na Pesquisa
-- ============================================
-- O usuário relatou que a pesquisa funciona quando especifica grupo = 1002
-- Mas não funciona quando não especifica grupo
-- ============================================

-- 1. Verificar quantos produtos existem no total
SELECT COUNT(*) AS TOTAL_PRODUTOS
FROM PRODUTOESERVICO;

-- 2. Verificar produtos por grupo
SELECT 
    COALESCE(GRUPO, 0) AS GRUPO,
    COUNT(*) AS QUANTIDADE
FROM PRODUTOESERVICO
GROUP BY GRUPO
ORDER BY GRUPO;

-- 3. Verificar produtos sem grupo (NULL ou 0)
SELECT COUNT(*) AS PRODUTOS_SEM_GRUPO
FROM PRODUTOESERVICO
WHERE GRUPO IS NULL OR GRUPO = 0;

-- 4. Verificar produtos do grupo 1002
SELECT COUNT(*) AS PRODUTOS_GRUPO_1002
FROM PRODUTOESERVICO
WHERE GRUPO = 1002;

-- 5. Testar busca "FRANGO" SEM filtro de grupo (deveria retornar todos)
SELECT FIRST 50 SKIP 0
    p3.ID, 
    p3.DESCRICAO, 
    p3.GRUPO,
    p3.ATIVO
FROM PRODUTOESERVICO p3
LEFT JOIN PRODUTO p1 ON p1.ID = p3.ID
WHERE 1=1
AND (
    (p1.CODIGOBARRA IS NOT NULL AND p1.CODIGOBARRA = 'FRANGO') OR
    (p3.DESCRICAO IS NOT NULL AND UPPER(p3.DESCRICAO) CONTAINING UPPER('FRANGO')) OR
    (p3.CARACTERISTICA IS NOT NULL AND UPPER(p3.CARACTERISTICA) CONTAINING UPPER('FRANGO')) OR
    (p3.CODIGOINTERNO IS NOT NULL AND p3.CODIGOINTERNO = 'FRANGO')
)
AND (p3.ATIVO = 1 OR p3.ATIVO IS NULL)
ORDER BY p3.DESCRICAO;

-- 6. Testar busca "FRANGO" COM grupo 1002 (funciona segundo o usuário)
SELECT FIRST 50 SKIP 0
    p3.ID, 
    p3.DESCRICAO, 
    p3.GRUPO,
    p3.ATIVO
FROM PRODUTOESERVICO p3
LEFT JOIN PRODUTO p1 ON p1.ID = p3.ID
WHERE 1=1
AND (
    (p1.CODIGOBARRA IS NOT NULL AND p1.CODIGOBARRA = 'FRANGO') OR
    (p3.DESCRICAO IS NOT NULL AND UPPER(p3.DESCRICAO) CONTAINING UPPER('FRANGO')) OR
    (p3.CARACTERISTICA IS NOT NULL AND UPPER(p3.CARACTERISTICA) CONTAINING UPPER('FRANGO')) OR
    (p3.CODIGOINTERNO IS NOT NULL AND p3.CODIGOINTERNO = 'FRANGO')
)
AND (p3.ATIVO = 1 OR p3.ATIVO IS NULL)
AND p3.GRUPO = 1002
ORDER BY p3.DESCRICAO;

-- 7. Verificar se há produtos com grupo diferente de 1002 que contêm "FRANGO"
SELECT 
    p3.GRUPO,
    COUNT(*) AS QUANTIDADE
FROM PRODUTOESERVICO p3
LEFT JOIN PRODUTO p1 ON p1.ID = p3.ID
WHERE 1=1
AND (
    (p1.CODIGOBARRA IS NOT NULL AND p1.CODIGOBARRA = 'FRANGO') OR
    (p3.DESCRICAO IS NOT NULL AND UPPER(p3.DESCRICAO) CONTAINING UPPER('FRANGO')) OR
    (p3.CARACTERISTICA IS NOT NULL AND UPPER(p3.CARACTERISTICA) CONTAINING UPPER('FRANGO')) OR
    (p3.CODIGOINTERNO IS NOT NULL AND p3.CODIGOINTERNO = 'FRANGO')
)
AND (p3.ATIVO = 1 OR p3.ATIVO IS NULL)
GROUP BY p3.GRUPO
ORDER BY p3.GRUPO;

-- 8. Verificar produtos ativos sem grupo
SELECT COUNT(*) AS ATIVOS_SEM_GRUPO
FROM PRODUTOESERVICO
WHERE (ATIVO = 1 OR ATIVO IS NULL)
AND (GRUPO IS NULL OR GRUPO = 0);

-- 9. Ver todos os produtos que contêm "FRANGO" (sem filtro de grupo)
SELECT 
    p3.ID,
    p3.DESCRICAO,
    p3.GRUPO,
    p3.ATIVO,
    p3.CODIGOINTERNO
FROM PRODUTOESERVICO p3
LEFT JOIN PRODUTO p1 ON p1.ID = p3.ID
WHERE 1=1
AND (
    (p1.CODIGOBARRA IS NOT NULL AND p1.CODIGOBARRA = 'FRANGO') OR
    (p3.DESCRICAO IS NOT NULL AND UPPER(p3.DESCRICAO) CONTAINING UPPER('FRANGO')) OR
    (p3.CARACTERISTICA IS NOT NULL AND UPPER(p3.CARACTERISTICA) CONTAINING UPPER('FRANGO')) OR
    (p3.CODIGOINTERNO IS NOT NULL AND p3.CODIGOINTERNO = 'FRANGO')
)
AND (p3.ATIVO = 1 OR p3.ATIVO IS NULL)
ORDER BY p3.GRUPO, p3.DESCRICAO;
