-- ============================================
-- QUERY DE BUSCA DE CLIENTES
-- ============================================
-- Esta é a query SQL que o sistema usa para buscar clientes
-- Busca por: Nome, Fantasia, CPF/CNPJ, Telefone ou Celular
-- ============================================

-- QUERY BASE (sem filtros)
SELECT FIRST 50 SKIP 0
    ID, NOME, CPFCNPJ, RGIE, TELEFONE, CELULAR, OBS, DATANAS,
    END1, NUM1, COMPL1, BAIRRO1, CIDADE1, UF1, EMAIL,
    END2, NUM2, COMPL2, BAIRRO2, CIDADE2, UF2,
    TABPRE, ATIVO, EMAIL1, CEP1, CEP2, CLASSIF, ACESSO, LIMITE,
    RG_ORGAO, RG_ESTADO, RG_EMISSAO, TELFAX, DT_CADASTRO,
    TIPO_PRODUTOR, IP, INCRA, NIRF, DECLA_ITR, CARRO,
    PLACA_CARRO1, PLACA_CARRO2, PLACA_CARRO3, MOTO,
    PLACA_MOTO1, PLACA_MOTO2, PLACA_MOTO3, FOTO, CEI,
    NUMPROPRIO, FANTASIA, CNAE, IDVENDEDOR, IBGE_UF,
    IBGE_MUNICIPIO, CONTRIBUINTE, MENSAL, SITE, BLOQUEADO, IDROTA
FROM CLIENTES
ORDER BY NOME;

-- ============================================
-- COM TERMO DE BUSCA
-- ============================================
-- Exemplo: buscar por "João" ou "12345678900" ou "11999999999"
SELECT FIRST 50 SKIP 0
    ID, NOME, CPFCNPJ, RGIE, TELEFONE, CELULAR, OBS, DATANAS,
    END1, NUM1, COMPL1, BAIRRO1, CIDADE1, UF1, EMAIL,
    END2, NUM2, COMPL2, BAIRRO2, CIDADE2, UF2,
    TABPRE, ATIVO, EMAIL1, CEP1, CEP2, CLASSIF, ACESSO, LIMITE,
    RG_ORGAO, RG_ESTADO, RG_EMISSAO, TELFAX, DT_CADASTRO,
    TIPO_PRODUTOR, IP, INCRA, NIRF, DECLA_ITR, CARRO,
    PLACA_CARRO1, PLACA_CARRO2, PLACA_CARRO3, MOTO,
    PLACA_MOTO1, PLACA_MOTO2, PLACA_MOTO3, FOTO, CEI,
    NUMPROPRIO, FANTASIA, CNAE, IDVENDEDOR, IBGE_UF,
    IBGE_MUNICIPIO, CONTRIBUINTE, MENSAL, SITE, BLOQUEADO, IDROTA
FROM CLIENTES
WHERE (
    UPPER(NOME) LIKE UPPER('%João%') OR
    UPPER(FANTASIA) LIKE UPPER('%João%') OR
    CPFCNPJ LIKE '%12345678900%' OR
    TELEFONE LIKE '%11999999999%' OR
    CELULAR LIKE '%11999999999%'
)
ORDER BY NOME;

-- ============================================
-- COM FILTRO DE ATIVO E NÃO BLOQUEADO
-- ============================================
-- Busca apenas clientes ativos e não bloqueados
SELECT FIRST 50 SKIP 0
    ID, NOME, CPFCNPJ, TELEFONE, CELULAR, FANTASIA, ATIVO, BLOQUEADO
FROM CLIENTES
WHERE (
    UPPER(NOME) LIKE UPPER('%João%') OR
    UPPER(FANTASIA) LIKE UPPER('%João%') OR
    CPFCNPJ LIKE '%12345678900%' OR
    TELEFONE LIKE '%11999999999%' OR
    CELULAR LIKE '%11999999999%'
)
AND ATIVO = 1
AND BLOQUEADO = 0
ORDER BY NOME;

-- ============================================
-- EXEMPLOS DE BUSCA
-- ============================================

-- Buscar por nome
SELECT FIRST 20 ID, NOME, CPFCNPJ, TELEFONE, CELULAR
FROM CLIENTES
WHERE UPPER(NOME) LIKE UPPER('%João%')
AND ATIVO = 1
AND BLOQUEADO = 0
ORDER BY NOME;

-- Buscar por CPF/CNPJ (sem formatação)
SELECT FIRST 20 ID, NOME, CPFCNPJ, TELEFONE, CELULAR
FROM CLIENTES
WHERE CPFCNPJ LIKE '%12345678900%'
AND ATIVO = 1
AND BLOQUEADO = 0
ORDER BY NOME;

-- Buscar por telefone (sem formatação)
SELECT FIRST 20 ID, NOME, CPFCNPJ, TELEFONE, CELULAR
FROM CLIENTES
WHERE TELEFONE LIKE '%11999999999%' OR CELULAR LIKE '%11999999999%'
AND ATIVO = 1
AND BLOQUEADO = 0
ORDER BY NOME;

-- ============================================
-- DIAGNÓSTICO
-- ============================================

-- Verificar quantos clientes existem
SELECT COUNT(*) AS TOTAL_CLIENTES FROM CLIENTES;

-- Verificar clientes ativos
SELECT COUNT(*) AS CLIENTES_ATIVOS FROM CLIENTES WHERE ATIVO = 1;

-- Verificar clientes não bloqueados
SELECT COUNT(*) AS CLIENTES_NAO_BLOQUEADOS FROM CLIENTES WHERE BLOQUEADO = 0;

-- Verificar clientes com telefone
SELECT COUNT(*) AS COM_TELEFONE FROM CLIENTES WHERE TELEFONE IS NOT NULL AND TELEFONE <> '';

-- Verificar clientes com celular
SELECT COUNT(*) AS COM_CELULAR FROM CLIENTES WHERE CELULAR IS NOT NULL AND CELULAR <> '';

-- Verificar clientes com CPF/CNPJ
SELECT COUNT(*) AS COM_CPF_CNPJ FROM CLIENTES WHERE CPFCNPJ IS NOT NULL AND CPFCNPJ <> '';

-- Ver alguns clientes de exemplo
SELECT FIRST 10 ID, NOME, CPFCNPJ, TELEFONE, CELULAR, ATIVO, BLOQUEADO
FROM CLIENTES
ORDER BY NOME;
