-- ============================================
-- QUERIES DE TESTE PARA DIAGNOSTICAR PRODUTOS
-- ============================================

-- 1. Contar total de produtos na tabela PRODUTOESERVICO
SELECT COUNT(*) AS TOTAL_PRODUTOS FROM PRODUTOESERVICO;

-- 2. Contar produtos ativos (ATIVO = 1 ou NULL)
SELECT COUNT(*) AS PRODUTOS_ATIVOS 
FROM PRODUTOESERVICO 
WHERE ATIVO = 1 OR ATIVO IS NULL;

-- 3. Contar produtos inativos (ATIVO = 0)
SELECT COUNT(*) AS PRODUTOS_INATIVOS 
FROM PRODUTOESERVICO 
WHERE ATIVO = 0;

-- 4. Verificar distribuição de produtos por grupo
SELECT GRUPO, COUNT(*) AS QUANTIDADE
FROM PRODUTOESERVICO
GROUP BY GRUPO
ORDER BY GRUPO;

-- 5. Buscar produtos SEM filtros (todos os produtos)
SELECT FIRST 10
    p3.ID, 
    p3.DESCRICAO, 
    p3.ATIVO, 
    p3.GRUPO,
    p1.CODIGOBARRA,
    p4.PRECOVENDA
FROM PRODUTOESERVICO p3
LEFT JOIN PRODUTO p1 ON p1.ID = p3.ID
LEFT JOIN PRODUTOEMPRESA p2 ON p2.ID = p3.ID
LEFT JOIN PRODUTOESERVICOEMPRESA p4 ON p4.ID = p3.ID
ORDER BY p3.DESCRICAO;

-- 6. Buscar produtos ATIVOS sem termo de busca
SELECT FIRST 10
    p3.ID, 
    p3.DESCRICAO, 
    p3.ATIVO, 
    p3.GRUPO,
    p1.CODIGOBARRA,
    p4.PRECOVENDA
FROM PRODUTOESERVICO p3
LEFT JOIN PRODUTO p1 ON p1.ID = p3.ID
LEFT JOIN PRODUTOEMPRESA p2 ON p2.ID = p3.ID
LEFT JOIN PRODUTOESERVICOEMPRESA p4 ON p4.ID = p3.ID
WHERE (p3.ATIVO = 1 OR p3.ATIVO IS NULL)
ORDER BY p3.DESCRICAO;

-- 7. Buscar produtos de um grupo específico (exemplo: grupo 1002)
SELECT FIRST 10
    p3.ID, 
    p3.DESCRICAO, 
    p3.ATIVO, 
    p3.GRUPO,
    p1.CODIGOBARRA,
    p4.PRECOVENDA
FROM PRODUTOESERVICO p3
LEFT JOIN PRODUTO p1 ON p1.ID = p3.ID
LEFT JOIN PRODUTOEMPRESA p2 ON p2.ID = p3.ID
LEFT JOIN PRODUTOESERVICOEMPRESA p4 ON p4.ID = p3.ID
WHERE (p3.ATIVO = 1 OR p3.ATIVO IS NULL)
AND p3.GRUPO = 1002
ORDER BY p3.DESCRICAO;

-- 8. Buscar produtos SEM grupo (GRUPO IS NULL ou GRUPO = 0)
SELECT FIRST 10
    p3.ID, 
    p3.DESCRICAO, 
    p3.ATIVO, 
    p3.GRUPO,
    p1.CODIGOBARRA,
    p4.PRECOVENDA
FROM PRODUTOESERVICO p3
LEFT JOIN PRODUTO p1 ON p1.ID = p3.ID
LEFT JOIN PRODUTOEMPRESA p2 ON p2.ID = p3.ID
LEFT JOIN PRODUTOESERVICOEMPRESA p4 ON p4.ID = p3.ID
WHERE (p3.ATIVO = 1 OR p3.ATIVO IS NULL)
AND (p3.GRUPO IS NULL OR p3.GRUPO = 0)
ORDER BY p3.DESCRICAO;

-- 9. Buscar produtos com termo de busca (exemplo: "FRANGO")
SELECT FIRST 10
    p3.ID, 
    p3.DESCRICAO, 
    p3.ATIVO, 
    p3.GRUPO,
    p1.CODIGOBARRA,
    p4.PRECOVENDA
FROM PRODUTOESERVICO p3
LEFT JOIN PRODUTO p1 ON p1.ID = p3.ID
LEFT JOIN PRODUTOEMPRESA p2 ON p2.ID = p3.ID
LEFT JOIN PRODUTOESERVICOEMPRESA p4 ON p4.ID = p3.ID
WHERE (
    (p1.CODIGOBARRA IS NOT NULL AND p1.CODIGOBARRA = 'FRANGO') OR
    (p3.DESCRICAO IS NOT NULL AND UPPER(p3.DESCRICAO) CONTAINING UPPER('FRANGO')) OR
    (p3.CARACTERISTICA IS NOT NULL AND UPPER(p3.CARACTERISTICA) CONTAINING UPPER('FRANGO')) OR
    (p3.CODIGOINTERNO IS NOT NULL AND p3.CODIGOINTERNO = 'FRANGO')
)
AND (p3.ATIVO = 1 OR p3.ATIVO IS NULL)
ORDER BY p3.DESCRICAO;

-- 10. Verificar se há produtos sem dados nas tabelas relacionadas
SELECT 
    COUNT(*) AS TOTAL,
    COUNT(p1.ID) AS COM_PRODUTO,
    COUNT(p2.ID) AS COM_PRODUTOEMPRESA,
    COUNT(p4.ID) AS COM_PRODUTOESERVICOEMPRESA
FROM PRODUTOESERVICO p3
LEFT JOIN PRODUTO p1 ON p1.ID = p3.ID
LEFT JOIN PRODUTOEMPRESA p2 ON p2.ID = p3.ID
LEFT JOIN PRODUTOESERVICOEMPRESA p4 ON p4.ID = p3.ID
WHERE (p3.ATIVO = 1 OR p3.ATIVO IS NULL);
